# -*- coding: utf-8 -*-
"""numpy all notebook .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/132jjjM_EW1VFKN7tS007xOB4qTFxuznG
"""

#numpy handles  fast calclutations.arrays,matrix, operations, and data prepestation for ml

#1D only rows and columns
import numpy as np
marks = np.array([10,20,30,40])
print(marks)
marks.ndim

#2D collection of one dimetional array
import numpy as np
marks=np.array([
    [1,2,3],
    [2,3,4]
])
print(marks)

marks.ndim

#3D  collection of 2 dimentonal arrays is known as 3D array
import numpy as np
marks=np.array([
    [[1,2],[1,2]],
    [[4,5],[4,5]]
])
print(marks)


marks.ndim
marks.shape

import numpy as np
marks=np.array([
  [[1,2],[2,3]],
   [[2,0], [9,0]]
])
print(marks)
print("dimentional of array:",marks.ndim)
print("dimentional of shape:",marks.shape)
print("dimentional of size:",marks.size)
print("dimentional of dtype:",marks.dtype)

marks = np.array([[10,20,30,40],[1,2,23,4]])
print(marks)
print("dimentional of ndim:",marks.ndim)
print("dimentional of shape:",marks.shape)
print("dimentional of size:",marks.size)

#Vectorization means performing an operation on an entire NumPy array at once. without using

#array creation functions:

import numpy as np
arr= np.zeros(10)#feel array with zeros
arr2= np.ones(10)# feel array with ones
arr3= np.full(10,50)# feel array with user specify number for ex: (20,25,4)
arr4= np.empty(500)
print(arr)
print(arr2)
print(arr3)
print(arr4)

import numpy as np
arr= np.zeros((2,3))
print(arr)

import numpy as np
arr= np.zeros((5,2))

import numpy as np
arr= np.ones((2,3))
print(arr)

import numpy as np
arr= np.full((10,10),6)
print(arr)

"""Number sequence:

"""

import numpy as np
array= np.linspace(0,40,4)# start stop partition (equal part)
print(array)

import numpy as np
arr=np.arange(0,9)
arr1=np.arange(20,41)
print(arr)
print(arr1)

#  create one array enter a number
import numpy as np
arr=np.array([10,20,30,40])
arr1= np.mean(arr)
arr2=np.average(arr)
arr3= np.median(arr)
print(arr)
print("dimentional of dtype:",arr.dtype)
print(arr1)
print(arr2)

print(arr3)
print(arr[0])
print(arr[1])
print(arr[2])

print(arr[0])
print(arr[-1])
print(arr[-2])

# solve question numpy
import numpy as np
arr=np.array([1,2,3,4,5,6])
arr1= np.ndim(arr)
arr2=np.shape(arr)
arr3= np.size(arr)
arr4= np.mean(arr)
arr5 = np.median(arr)




print(arr)
print(arr1)
print(arr2)
print(arr3)
print(arr4)
print(arr5)

import numpy as np
arr= np.array([[1,2,3,4,5],
               [6,7,8,9,10]])

print(arr[-1,])# row and column
print(arr[1,]) # row nad column
print(arr[0,])

print(arr[:, 0])

# every element in anumpy array can be accessed by its postion(inder) ,starting from 0, Neagtive indices countbabckwards from the end.

import numpy as np
arr= np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(arr[0,1])
print(arr[-1,-2])

import numpy as np
arr = np.array([[[1,2,3,4],
                 [5,6,7,8]],
                [[9,10,11,12],
                 [13,14,15,16]]])
print(arr)

print(arr[1,1,1])
print(arr[0,1,2])
print(arr[-2,-1,-1])
print(arr[-2,-1,])

import numpy as np # 1 D array
arr= np.array([1,2,3,4])
print(arr)

import numpy as np
arr= np.array([[1,2,3,4],
               [5,6,7,8]
               ])
print(arr)

import numpy as np
arr= np.array([[[1,2,3,4],
               [5,6,7,8]],
              [[10,11,12,13],
              [14,15,16,17]]])



print=np.shape(arr)
print=np.size(arr)
print= np.ndim(arr)

import numpy as np
arr= np.array([1,2,3,4,5])
print(arr)
print(arr[2])
print(arr[-1])

import  numpy as np
arr= np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15]])
print(arr)
print(arr[-2,-4])
print(arr[2,2])

"""
# What is indexing in numpy?
# -->Access the element by using index value,

#  What is Slicing?
--> Licing means taking a part/portion of a sequence such as a string, list, or tuple.
# fancy indexing


Fancy indexing in NumPy is a method of accessing multiple specific elements using an array or list of indices..
"""

import numpy as np
arr= np.array([1,2,3,4,5,6,7,8,9])
print(arr)

print(arr[0:10])
print(arr[-7:-5])# last value / stop value will be skip.
print(arr[::1])# reverse  values print
print(arr[::-1])
print(arr[::2]) # start  stop step: skip the value as per value

import numpy as np
arr = np.array([[1,2],
               [3,4],
               [5,6],
               [7,8],
               [9,10]])

print(arr[1 :4, :1 ])

import numpy as  np
arr = np.array([[1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15],
                [16,17,18,19,20]])
print(arr[2:,:2])

import numpy as  np
arr = np.array([[1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15],
                [16,17,18,19,20]],
)
print(arr[2:,:2])

import numpy as np
arr= np.array([[[1,2,3],
              [4,5,6],
              [7,8,9],
              [10,11,12],
               [13,14,15]  ]])
print(arr.ndim)
print(arr[0,1,2])
print(arr[0,-1,-1])
print([[1,-3] ,[0,2]])

import numpy as np
arr= np.array([1,2,3,4,5,6,7,8,9])
print(arr)
print([[1,-3] ,[0,2]])

import numpy as np
arr = np.array([10,20,30,40,50])
print(arr[[4,0,2]])

import numpy as np
arr=np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]]
  )
print(arr[[0,2]])
print(arr[:,[0,2]]) #row (INDEX   WHICH WE WANT ),COL(INDEX WHICH WE WANT )
print(arr[1,1])
print(arr[[0,2]])
print(arr[:,[0,1]])

import numpy as np

arr = np.array([[[1, 2, 3, 4],
                 [5, 6, 7, 8]],

                [[11, 12, 13, 14],
                 [15, 16, 17, 18]],

                [[11, 12, 13, 14],
                 [15, 16, 17, 18]]])

print(arr[1, 0, 2]) # indexing
print(arr[[1], [0], [0, 2] f]) # fancy indexing

import numpy as np
arr=np.array([[[1,2],
             [3,4],
             [5,6]]])
print(arr)
print(arr.ndim)

# Where

import numpy as np
arr=np.array([[1,2,3,4],
              [5,6,7,8]])
print(arr.ndim)
print(np.where(arr==2)) # use to find index
print(np.where(arr==6))
print(np.nonzero(arr))
print(arr[1,2])

# np.argwhere  convert into one dm and thret as a non zero index
import numpy as np
arr=np.array([[1,2,3,4],
              [5,6,7,8]])

print(np.argwhere(arr==5))

#argmax
import numpy as np
arr=np.array([1,2,3,4])
print(np.argmax(arr))
print(np.argmax(arr))

#  MAX

import numpy as np
arr=np.array([[1,2,3,4],
              [5,6,7,8]])
print(np.argmin(arr))
print(np.max(arr))

# all condition  shoulld be satisfy,
# any one conditon should be  satisfy ,

import numpy as np
arr=np.array([[1,2,3,4],
              [5,6,7,8]])
print(np.any(arr>0))
print(np.all(arr>7))
print(np.all(arr>7))

"""# where(),argwhere(),max,argmax(),all,any,nonzero,min(),argmin();

#View & copy      view() = Same data, different way to see it  copy() = Completely separate data
# View :when i will update the value in array by using new variable it will update in original array
#Copy: when it update the value by using new variables, a cop
"""

import numpy as np
arr=np.array([1,2,3,4,5])
arr1= arr[1:4]
arr[0]=10000
print(arr1)
print(arr)

""" #why is view usefuly
  #save memory,avoids unnsessary copy, faster than copy

  #disa advantages(View): It can cause accidental modification of data
"""

