# -*- coding: utf-8 -*-
"""numpy all notebook .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/132jjjM_EW1VFKN7tS007xOB4qTFxuznG
"""

#numpy handles  fast calclutations.arrays,matrix, operations, and data prepestation for ml

#1D only rows and columns
import numpy as np
marks = np.array([10,20,30,40])
print(marks)
marks.ndim

#2D collection of one dimetional array
import numpy as np
marks=np.array([
    [1,2,3],
    [2,3,4]
])
print(marks)

marks.ndim

#3D  collection of 2 dimentonal arrays is known as 3D array
import numpy as np
marks=np.array([
    [[1,2],[1,2]],
    [[4,5],[4,5]]
])
print(marks)


marks.ndim
marks.shape

import numpy as np
marks=np.array([
  [[1,2],[2,3]],
   [[2,0], [9,0]]
])
print(marks)
print("dimentional of array:",marks.ndim)
print("dimentional of shape:",marks.shape)
print("dimentional of size:",marks.size)
print("dimentional of dtype:",marks.dtype)

marks = np.array([[10,20,30,40],[1,2,23,4]])
print(marks)
print("dimentional of ndim:",marks.ndim)
print("dimentional of shape:",marks.shape)
print("dimentional of size:",marks.size)

#Vectorization means performing an operation on an entire NumPy array at once. without using

#array creation functions:

import numpy as np
arr= np.zeros(10)#feel array with zeros
arr2= np.ones(10)# feel array with ones
arr3= np.full(10,50)# feel array with user specify number for ex: (20,25,4)
arr4= np.empty(500)
print(arr)
print(arr2)
print(arr3)
print(arr4)



import numpy as np
arr= np.zeros((2,3))
print(arr)

import numpy as np
arr= np.zeros((5,2))

import numpy as np
arr= np.ones((2,3))
print(arr)

import numpy as np
arr= np.full((10,10),6)
print(arr)

"""Number sequence:

"""

import numpy as np
array= np.linspace(0,40,4)# start stop partition (equal part)
print(array)

import numpy as np
arr=np.arange(0,9)
arr1=np.arange(20,41)
print(arr)
print(arr1)

#  create one array enter a number
import numpy as np
arr=np.array([10,20,30,40])
arr1= np.mean(arr)
arr2=np.average(arr)
arr3= np.median(arr)
print(arr)
print("dimentional of dtype:",arr.dtype)
print(arr1)
print(arr2)

print(arr3)
print(arr[0])
print(arr[1])
print(arr[2])

print(arr[0])
print(arr[-1])
print(arr[-2])

# solve question numpy
import numpy as np
arr=np.array([1,2,3,4,5,6])
arr1= np.ndim(arr)
arr2=np.shape(arr)
arr3= np.size(arr)
arr4= np.mean(arr)
arr5 = np.median(arr)




print(arr)
print(arr1)
print(arr2)
print(arr3)
print(arr4)
print(arr5)

