# -*- coding: utf-8 -*-
"""OOPS ALL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IxiRl-FGRjOJ8grheJhoPiWQ9wKF9sPr
"""

# class is a blueprint for creating objects.
# Creating class
class Student:
   name="Yash"
   age=23

s1=Student()
print(s1.name)
print(s1.age)


#creating object (instance)

#__init__ function:
# Constructor:
# all classes have a Function called_init_(),which is always excuted when the class is being initiated.
# self meaning jo object create hota hey use self a
 #((Varibles called Atributes.))

# deafult constructors & parameterize constructor
# Methods: Methods are functions That belong to objects.

class Student:

  def __init__(self,fullname):
    self.name = fullname
    print("Adding new student in database.")

    s1=(self.name)

class Student:

  def __init__(self,fullname,marks):
    self.name = fullname
    self.marks = marks
    print("Adding new student in database.")

    s1= Student("Yash",90)
    print(s1.name,s1.marks)

    s2 = Student("Yash",77)
    print(s2.name,s2.marks)

# class Student:

  def __init__(self,fullname,marks):
    self.name = fullname
    self.marks = marks
    print("Adding new student in database.")

    s1= Student("Yash",90)
    print(s1.name,s1.marks)

    s2 = Student("Yash",77)
    print(s2.name,s2.marks)

class Student:
  college_name = "ASM COLLEGE"


def __init__(self,name,marks):
  self.name =name
  self.marks = marks

  def welcome(self):
    print("Welcome to college",self.name)

  def get_marks(self):
      return self.marks


  s1 = Student("Yash",00)
  s1.welcome()
  print(s1.gets_marks())

class Yash:

  def __init__(self,name,marks):
    self.name = name
    self.marks = marks


def get_avg(self):
  sum = 0
  for val in self.marks:
       sum += val
  print("hi",self.name,"your avg score is:",sum/3)

  s1 = Student("Yashuuu",[10,20,30])
  s1.get_avg()

#Static Methods: methods That dont use the self parameter(Work At class Level)
#syntax:
# class Student:
#  @staticmethod   #decorator
#    def college():
#     print("ABC College")



#Static Methods: methods That dont use the self parameter(Work At class Level)
#syntax:
# class Student:
#  @staticmethod   #decorator
#    def college():
#     print("ABC College")

# inheritance: deriving prop of one class to another is called
#type: 1single level

class Parent:
  parent_name = "parent"

  def __init__(self,age):
    self,age=age

    def display(self,sal):
      self.sal=sal
      print("parent class:",self.sal)


  class Child(Parent):
     child_name =  "child"

     def __init_(self,child_age,age)

# # important
# abstraction:
# hiding the implementation deatils of a class only showing the essential features to the user.

# Encapsulation:
# Wrapping data and functions into a single unit (objects.)

class Account:
  def __init__(self,bal,acc):
    self.balance = bal
    self.account_no = acc


  def debit(self,amount):
      self.balance -= amount
      print("Rs.",amount,"Was debited")
      print("total balance =",self.get_balance())


  def credit(self,amount):
        self.balance +=amount
        print("Rs",amount,"Was credited")
        print("total balance =,self.get_balance")


  def get_balance(self):
        return self.balance

acc1 = Account(1000,2000)
acc1.debit(1000)
acc1.credit(1000)
acc1.credit(10000)

class Parent:  # memory: box create
    parent_name = "parent"

    def __init__(self, age):
        self.age = age

    def display(self, sal):
        self.sal = sal
        print("parent sal:", self.sal)


class Child(Parent):  # child box
    child_name = "child"

    def __init__(self, child_age, age):
        super().__init__(age)
        self.child_age = child_age

    def display(self, child_sal, sal):
        super().display(sal)
        self.child_sal = child_sal
        print("parent sal:", self.child_sal)


c = Child(20, 40)

print("child name:", c.child_name)

# multilevel inheritance:

##(())
# class Ram:
#   name = "yashodip"

# s1 = Ram()
# print(s1.name)

# s2 = Ram()
# print(s2.name)

class Ram:

  def __init__(self,fullname):
      self.name= fullname
      print("Adding new student in database.")
s1 = Ram("Yashodip")
print(s1.name)

class Rom:
  @staticmethod
  def __init__(self,name,marks):
    self.name=name
    self.marks=marks

  def get_avg(self):
    sum=0
    for val in self.marks:
      sum+=val
    print("hi",self.name,"your avg score is:",sum/3)



s1=Rom("Yash",[0,10,90])
print(s1.name,s1.marks)

#static method:

class Parent:  # parent box
    parent_name = "parent"

    def __init__(self, age):
        self.age = age

    def display(self, sal):
        self.sal = sal
        print("parent sal:", self.sal)


class Child(Parent):  # child box
    child_name = "child"

    def __init__(self, child_age):
        super().__init__(age)
        self.child_age = child_age

    def display(self, child_sal, sal):
        super().display(sal)
        self.child_sal = child_sal
        print("parent sal:", self.child_sal)


class Grand_child(Child):
    grand_name = "GRAND CHILD"

    def __init__(self, grand_age, child_age):
        super().__init__(child_age)
        self.grand_age = grand_age

    def display(self, grand_sal, child_sal, sal):
        super().display(child_sal, sal)
        self.grand_sal = grand_sal
        print("parent sal:", self.grand_sal)


b = Grand_child(10, 30, 70)

print("grand age :", b.grand_age)  # 10

b.display(50, 20000, 10000)

print("child name :", b.child_name)

class Fruit:
    loc = "find loc"

    def __init__(self, color):
        self.color = color

    def taste(self):
        print("class '__main__.Fruit'")


class Apple(Fruit):
    loc1="maharastra"

    def __init__(self, apple_color, color):
        super().__init__(color)
        self.apple_color = apple_color

    def taste(self, test):
        super().taste()
        self.test = test
        print("taste:", self.test)


class Mango(Fruit):
    loc2="mumbai"

    def __init__(self, mango_color, color):
        super().__init__(color)
        self.mango_color = mango_color

    def taste(self, mango_test):
        super().taste()
        self.mango_test = mango_test
        print("taste of mango:", self.mango_test)


a = Apple("red", "color")
m = Mango("yellow", "color")

print("color :", a.apple_color)
print("color :", m.mango_color)

print(a.loc)
print(a.loc1)
print(m.loc2)

class std:
   def __init__(self,name):
    self.name=name

   def display(self,work):
    self.work=work

class son(parent):
  def __init__(self,son_name,name)
  super().__init(name)
  self.name=name


def display(self,son_work,work):
  super().display(work)
  self.son_work=son_work


class yz(parent):
    def __init__(self,yz_name,son_name,name)
  super().__init__(son_name,name)
  self.yz_name=yz_name


def display(self,yz_name,son_work,work):
  super().display(yz_name,work)
  self.yz_work=yz_work

A1=(yash)

class India:
   population1=40000000000000

  def lang(self):
    print("language of india.")

  class maharastra(India):

class Parent:
    def __init__(self, name=""):
        self.name = name

    def display(self, work):
        self.work = work
        print("Parent Name:", self.name)
        print("Parent Work:", self.work)


class Son(Parent):
    def __init__(self, son_name, name):
        super().__init__(name)
        self.son_name = son_name

    def display(self, son_work, work):
        super().display(work)
        self.son_work = son_work
        print("Son Name:", self.son_name)
        print("Son Work:", self.son_work)


class Daughter(Parent):
    def __init__(self, dau_name, name):
        super().__init__(name)
        self.dau_name = dau_name

    def display(self, dau_work, work):
        super().display(work)
        self.dau_work = dau_work
        print("Daughter Name:", self.dau_name)
        print("Daughter Work:", self.dau_work)


class Child(Son, Daughter):
    def __init__(self, child_work, son_name, dau_name, name):
        Son.__init__(self, son_name, name)
        self.dau_name = dau_name
        self.child_work = child_work

    def display(self):
        print("Parent Name:", self.name)
        print("Son Name:", self.son_name)
        print("Daughter Name:", self.dau_name)
        print("Child Work:", self.child_work)

f1 = Child("Student", "Rahul", "Priya", "Ramesh")
f1.display()

class Employee:
    def __init__(self, name):
        self.name = name

    def work(self):
        print(self.name, "is an Employee.")


class Developer(Employee):
    def __init__(self, name):
        super().__init__(name)

    def code(self):
        print(self.name, "writes code.")


class Tester(Employee):
    def __init__(self, name):
        super().__init__(name)

    def test(self):
        print(self.name, "tests software.")


class Manager(Developer, Tester):
    def __init__(self, name):
        super().__init__(name)

    def manage(self):
        print(self.name, "manages the team.")


m = Manager("Yashuuuuu")

m.work()
m.code()
m.test()
m.manage()

class Employee:
    def __init__(self, name):
        self.emp = name

    def display(self):
        print("Employee:", self.emp)


class Developer(Employee):
    def __init__(self, name):
        Employee.__init__(self, name)
        self.dev = name

    def display(self):
        print("Developer:", self.dev)


class Tester(Employee):
    def __init__(self, name):
        Employee.__init__(self, name)
        self.test = name

    def display(self):
        print("Tester:", self.test)


class Manager(Developer, Tester):
    def __init__(self, emp, dev, test, manager):
        self.emp = emp
        self.dev = dev
        self.test = test
        self.manager = manager

    def display(self):
        print("Employee:", self.emp)
        print("Developer:", self.dev)
        print("Tester:", self.test)
        print("Manager:", self.manager)


m = Manager("Yash", "Vijay", "Akib", "Dhananjay")
m.display()

class Employee:
    # Employee class
    def __init__(self, field):
        self.field = field

    def display(self, work):
        print("Consultant employee:", work)


class Developer(Employee):
    def __init__(self, dev_field, field):
        Employee.__init__(self, field)
        self.dev_field = dev_field

    def display(self, work1, work):
        Employee.work = work
        print("Consultant developer:", self.work1)


class Tester(Employee):
    def __init__(self, test_field, dev_field, field):
        Employee.__init__(self, field)
        self.test_field = test_field

    def display(self, work2, work):
        Employee.work2 = work2
        print("Consultant employee:", self.work2)


class Manager(Developer, Tester):
    def __init__(self, manage, test_field, dev_field, field):
        Employee.__init__(self, field)
        Developer.__init__(self, dev_field, field)
        Tester.__init__(self, test_field, dev_field, field)
        self.manage = manage

    def display(self, work3, work2, work1, work):
        self.work3 = work3
        print("Work of manager:", self.work3)


# Create object
obj1 = Manager("managing", "testing", "develop", "help")

# Display manager's data
print(obj1.manage)

# Call display function
obj1.display("managing", "testing", "develop", "help")

Def add(a,b):
  Return a+b
Def add (a,b,c):
  Return a+b_c
Print(add(10,20,30))

class Flipkart:
    def __init__(self, data):
        self.data = data

    def order(self):
        print("Ordered data")

    def __add__(self, other):
        return self.data + " and " + other.data + " is ordered"


class Clothes(Flipkart):
    def order(self):
        # super().order()
        print(f"{self.data} clothes are ordered")


class Mobile(Flipkart):
    def order(self):
        super().order()
        print(f"{self.data} mobile is ordered")


o1 = Mobile("iPhone")
o2 = Clothes("Puma shirt")

o1.order()
o2.order()

print(o1 + o2)

#encapsulation:

class Bankaccount():
  def __init__(self,balance):
    self.balance=balance

    def deposit(self,amount):
      self.balance +=amount

    def withdraw(self,amount):
      self.balance -= amount

b = Bankaccount(1000)
print(b.__balance)
b.deposit(500)


b =bankaccount(1000)
b.deposit(500)
print(b.balance)

class Bankaccount():
  def __init__(self,balance):
    self.balance=balance

  def get __balance(self):
      return self.balance


 def set __balance(self,balance):
    if amount > 0
    self. __(amount)
print("f(amount) added in your account")

    else:
      print("ammount invalaid")
      b = bankaccount(99000)
  b.get_balance()
  b.get_balance(5000)
  b.get_balance()

class BankAccount:

    def __init__(self, balance):
        self.__balance = balance

    def get_balance(self):
        return self.__balance

    def set_balance(self, amount):
        if amount > 0:
            self.__balance += amount
            print(f"{amount} added in your account")
        else:
            print("Amount invalid")


b = BankAccount(50000)

print(b.get_balance())

b.set_balance(500)

print(b.get_balance())

class Student:

    def __init__(self, marks):
        self.__marks = marks


    def get_marks(self):
        return self.__marks


    def set_marks(self, marks):
        if marks >= 0 and marks <= 100:
            self.__marks = marks
            print("Marks updated successfully")
        else:
            print("Invalid marks! Marks should be between 0 and 100")



s = Student(70)


print("Marks:", s.get_marks())


s.set_marks(50)

print("Marks:", s.get_marks())


s.set_marks(80)
print("Updated Marks:", s.get_marks())

