# -*- coding: utf-8 -*-
"""Untitled59.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BORCtGPg2R7iwuPNRcS4kMsmwfMgDo6A
"""

class BankAccount:
    def __init__(self, name, balance):
        self.name = name
        self.__balance = balance

    def get_balance(self):
        return self.__balance

    def set_balance(self, amount):
        if amount >= 0:
            self.__balance = amount

            if amount >= 100000:
                proof = input("From where did you bring this much money? Give us proof: ")
                print("Proof received:", proof)

        else:
            print("Balance cannot be negative!")

    def deposit(self, amount):
        if amount > 0:
            self.__balance += amount

            if self.__balance >= 100000:
                proof = input("Your balance is above ₹1,00,000. Give us proof: ")
                print("Proof received:", proof)

        else:
            print("You can't deposit a negative amount!")

    def withdraw(self, amount):
        if 0 < amount <= self.__balance:
            self.__balance -= amount
        else:
            print("Invalid withdrawal amount!")


account = BankAccount("Vijay", 50000)

account.set_balance(25000)
account.withdraw(0)
account.withdraw(50)

print("Final balance:", account.get_balance())

